import type { Locale } from "./i18n";

// Maps database errors (raised by constraints, triggers and RPCs) to clear bilingual
// messages for staff. Unknown errors fall back to a safe generic message; the original
// text is kept for logs, never shown raw.

type Rule = { match: RegExp; ar: string; en: string };

const RULES: Rule[] = [
  { match: /no_doctor_overlap/, ar: "الطبيب لديه موعد آخر في هذا الوقت.", en: "The doctor already has an appointment at this time." },
  { match: /no_room_overlap/, ar: "الغرفة محجوزة في هذا الوقت.", en: "The room is already booked at this time." },
  { match: /invalid phone number/, ar: "رقم الموبايل غير صحيح.", en: "The mobile number is not valid." },
  { match: /patients_national_id_uq|duplicate key.*national_id/, ar: "هذا الرقم القومي مسجل لمريض آخر.", en: "This national ID belongs to another patient." },
  { match: /national_id_check|check constraint "patients_national_id/, ar: "الرقم القومي يجب أن يكون 14 رقمًا.", en: "National ID must be 14 digits." },
  { match: /invalid appointment transition/, ar: "لا يمكن نقل الموعد إلى هذه الحالة من حالته الحالية.", en: "The appointment cannot move to that status from its current one." },
  { match: /cancel reason is required/, ar: "سبب الإلغاء مطلوب.", en: "A cancellation reason is required." },
  { match: /open a cashier session/, ar: "افتح وردية خزينة قبل استلام النقدية.", en: "Open a cashier session before receiving cash." },
  { match: /already have an open cashier session/, ar: "لديك وردية مفتوحة بالفعل.", en: "You already have an open session." },
  { match: /requires a reference/, ar: "طريقة الدفع هذه تتطلب رقم مرجع.", en: "This payment method requires a reference number." },
  { match: /exceeds outstanding balance/, ar: "المبلغ أكبر من المتبقي على الفاتورة.", en: "The amount exceeds the invoice balance." },
  { match: /cannot receive payments/, ar: "هذه الفاتورة لا تقبل دفعات في حالتها الحالية.", en: "This invoice cannot receive payments in its current status." },
  { match: /idempotency key reused/, ar: "تعارض في تسجيل الدفعة. أعد تحميل الصفحة وحاول مجددًا.", en: "Payment conflict. Reload the page and try again." },
  { match: /invoice has no lines/, ar: "أضف خدمة واحدة على الأقل قبل الإصدار.", en: "Add at least one service before issuing." },
  { match: /discount_within_line/, ar: "الخصم أكبر من قيمة البند.", en: "The discount exceeds the line value." },
  { match: /issued an invoice cannot void/, ar: "لا يمكن لنفس المستخدم الذي أصدر الفاتورة إلغاؤها. يلزم موافقة مستخدم آخر.", en: "The user who issued the invoice cannot void it; another authorized user must." },
  { match: /only issued invoices with no payments/, ar: "لا يمكن إلغاء فاتورة عليها دفعات. يلزم استرداد أولًا.", en: "Invoices with payments cannot be voided; refund first." },
  { match: /void reason is required|^reason is required/, ar: "السبب مطلوب.", en: "A reason is required." },
  { match: /note is required when counted cash differs/, ar: "يوجد فرق في النقدية. اكتب ملاحظة توضح السبب.", en: "Counted cash differs from expected. Add a note explaining why." },
  { match: /signed encounter cannot be modified/, ar: "الكشف موقّع ولا يمكن تعديله. أضف ملاحظة لاحقة.", en: "The encounter is signed. Add an addendum instead." },
  { match: /only the treating doctor/, ar: "التوقيع متاح للطبيب المعالج فقط.", en: "Only the treating doctor can sign." },
  { match: /no open fiscal period/, ar: "الفترة المحاسبية مغلقة أو غير معرفة لهذا التاريخ.", en: "No open fiscal period for this date." },
  { match: /is not configured/, ar: "إعدادات الحسابات غير مكتملة. تواصل مع رئيس الحسابات.", en: "Accounting settings are incomplete. Contact the chief accountant." },
  { match: /allergy acknowledgement required/, ar: "المريض لديه حساسية مسجلة. راجعها وأكّد الإقرار قبل التوقيع.", en: "The patient has a recorded allergy. Review it and confirm the acknowledgement before signing." },
  { match: /restricted medicine/, ar: "هذا الدواء ضمن القائمة المقيدة ويتطلب صلاحية خاصة.", en: "This medicine is on the restricted list and needs special authorization." },
  { match: /prescription has no items/, ar: "أضف دواءً واحدًا على الأقل.", en: "Add at least one medicine." },
  { match: /signed prescriptions cannot be changed/, ar: "الروشتة موقّعة ولا يمكن تعديلها.", en: "The prescription is signed and cannot be changed." },
  { match: /patient-facing summary is required/, ar: "اكتب ملخصًا مبسطًا للمريض قبل الإفراج.", en: "Write a patient-facing summary before releasing." },
  { match: /only signed records can be released/, ar: "يجب توقيع السجل أولًا.", en: "Sign the record first." },
  { match: /already released/, ar: "تم الإفراج عنه بالفعل.", en: "Already released." },
  { match: /evidence of relationship is required/, ar: "اكتب مستند إثبات صلة القرابة أو الولاية.", en: "Record the evidence of relationship or guardianship." },
  { match: /resolution note is required/, ar: "اكتب ما تم لحل الطلب قبل إغلاقه.", en: "Write the resolution before closing." },
  { match: /only failed messages can be retried/, ar: "يمكن إعادة المحاولة للرسائل الفاشلة فقط.", en: "Only failed messages can be retried." },
  { match: /refund reason is required/, ar: "اكتب سبب الاسترداد.", en: "Enter the reason for the refund." },
  { match: /exceeds the refundable amount/, ar: "المبلغ أكبر من المتاح للاسترداد على هذه الفاتورة.", en: "The amount exceeds what can be refunded on this invoice." },
  { match: /cannot approve your own refund/, ar: "لا يمكنك الموافقة على طلب استرداد قدّمته بنفسك. يلزم مسؤول آخر.", en: "You cannot approve a refund you requested; another approver is required." },
  { match: /note is required to reject/, ar: "اكتب سبب الرفض.", en: "Write the reason for rejecting." },
  { match: /must be approved before payment/, ar: "يجب اعتماد الاسترداد قبل صرفه.", en: "The refund must be approved before it is paid." },
  { match: /open a cashier session before paying cash/, ar: "افتح وردية خزينة قبل صرف نقدية.", en: "Open a cashier session before paying out cash." },
  { match: /refund already/, ar: "تم اتخاذ قرار في هذا الطلب بالفعل.", en: "This request has already been decided." },
  { match: /your own roles/, ar: "لا يمكنك تعديل صلاحياتك بنفسك.", en: "You cannot change your own roles." },
  { match: /your own account/, ar: "لا يمكنك إيقاف حسابك بنفسك.", en: "You cannot deactivate your own account." },
  { match: /already active for the user/, ar: "هذا الدور مفعّل للمستخدم بالفعل.", en: "This role is already active for the user." },
  { match: /end date must be in the future/, ar: "تاريخ الانتهاء يجب أن يكون في المستقبل.", en: "The end date must be in the future." },
  { match: /cannot approve a settlement you prepared/, ar: "لا يمكنك اعتماد كشف أعددته بنفسك. يلزم مسؤول آخر.", en: "You cannot approve a statement you prepared; another approver is required." },
  { match: /contract you entered/, ar: "لا يمكنك اعتماد كشف مبني على عقد أدخلته بنفسك.", en: "You cannot approve a statement based on a contract you entered." },
  { match: /approver cannot also record the payment/, ar: "من اعتمد الكشف لا يسجل صرفه. يلزم شخص آخر.", en: "The approver cannot also record the payment." },
  { match: /contract changed after this statement/, ar: "تغيّر العقد بعد إعداد الكشف. ألغِه وأعد إعداده.", en: "The contract changed after this statement was prepared. Cancel and prepare again." },
  { match: /without a contract/, ar: "في الكشف خدمات لطبيب بدون عقد سارٍ. أضف العقد ثم ألغِ الكشف وأعد إعداده.", en: "The statement has services with no valid contract. Add the contract, cancel and prepare again." },
  { match: /settlement_one_active_run|duplicate key.*settlement/, ar: "يوجد كشف لهذا الطبيب عن نفس الشهر بالفعل.", en: "A statement for this doctor and month already exists." },
  { match: /cannot settle a future month/, ar: "لا يمكن إعداد كشف لشهر لم يبدأ.", en: "You cannot settle a month that has not started." },
  { match: /only draft settlements can be cancelled/, ar: "يمكن إلغاء الكشوف غير المعتمدة فقط.", en: "Only draft statements can be cancelled." },
  { match: /must be approved before payment/, ar: "يجب اعتماد الكشف قبل الصرف.", en: "The statement must be approved before payment." },
  { match: /nothing to pay on this settlement/, ar: "لا يوجد مبلغ مستحق للصرف في هذا الكشف (يُرحّل الرصيد السالب).", en: "Nothing to pay on this statement (a negative balance is carried)." },
  { match: /settlement for this period is already approved/, ar: "يوجد كشف معتمد في هذه الفترة؛ يجب أن يبدأ العقد الجديد بعده.", en: "A statement for this period is approved; the new contract must start after it." },
  { match: /contract already starts on this date/, ar: "يوجد عقد يبدأ في نفس التاريخ.", en: "A contract already starts on this date." },
  { match: /used in an approved settlement/, ar: "هذا العقد استُخدم في كشف معتمد ولا يمكن تعديله. ابدأ عقدًا جديدًا.", en: "This contract was used in an approved statement. Start a new contract instead." },
  { match: /mandatory for privileged roles/, ar: "التحقق الثنائي إلزامي للأدوار الحساسة.", en: "Two-factor sign-in is mandatory for privileged roles." },
  { match: /own sign-in security/, ar: "لا يمكنك تعديل إعدادات دخولك بنفسك.", en: "You cannot change your own sign-in security." },
  { match: /insufficient stock for (\S+)/, ar: "الكمية المتاحة (غير المنتهية الصلاحية) لا تكفي لأحد الأصناف.", en: "Not enough usable (unexpired) stock for one of the items." },
  { match: /controlled item/, ar: "هذا الصنف خاضع للرقابة ويتطلب صلاحية خاصة للصرف.", en: "This is a controlled item and needs special authorization." },
  { match: /expiry date is required/, ar: "تاريخ انتهاء الصلاحية مطلوب لهذا الصنف.", en: "An expiry date is required for this item." },
  { match: /already expired/, ar: "لا يمكن استلام صنف منتهي الصلاحية.", en: "Expired goods cannot be received." },
  { match: /lot number is required/, ar: "رقم التشغيلة مطلوب.", en: "The lot number is required." },
  { match: /supplier invoice number is required/, ar: "رقم فاتورة المورد مطلوب.", en: "The supplier invoice number is required." },
  { match: /goods_receipts_supplier_id_supplier_invoice_no_key/, ar: "فاتورة المورد هذه مسجلة من قبل.", en: "This supplier invoice was already received." },
  { match: /choose the appointment or write the purpose/, ar: "اختر الموعد أو اكتب سبب الصرف.", en: "Choose the appointment or write the purpose of the issue." },
  { match: /a count is already open/, ar: "يوجد جرد مفتوح لهذا المخزن.", en: "A count is already open for this store." },
  { match: /enter a counted quantity for every lot/, ar: "أدخل الكمية المعدودة لكل تشغيلة.", en: "Enter a counted quantity for every lot." },
  { match: /approve your own count/, ar: "لا يمكنك اعتماد جرد قمت به. يلزم مسؤول آخر.", en: "You cannot approve your own count; another approver is required." },
  { match: /stock moved after the count/, ar: "تغيّر الرصيد بعد تقديم الجرد. ألغِه وأعد الجرد.", en: "Stock moved after the count was submitted. Cancel and count again." },
  { match: /count is in progress for this store/, ar: "يوجد جرد مفتوح لهذا المخزن؛ لا صرف ولا استلام حتى يُعتمد أو يُلغى.", en: "A count is in progress for this store; no issues or receipts until it is approved or cancelled." },
  { match: /too many decimals/, ar: "عدد الخانات العشرية أكبر من المسموح (الكمية 3، التكلفة 4).", en: "Too many decimals (quantity 3, cost 4)." },
  { match: /controlled-items authority/, ar: "تغيير تصنيف الصنف أو خضوعه للرقابة يتطلب صلاحية الأصناف الخاضعة للرقابة (المدير الطبي).", en: "Changing an item's category or controlled status needs the controlled-items authority (medical director)." },
  { match: /cannot approve a purchase order you created/, ar: "لا يمكنك اعتماد أمر شراء أنشأته. يلزم مسؤول آخر.", en: "You cannot approve a purchase order you created." },
  { match: /must be submitted before approval/, ar: "يجب إرسال أمر الشراء للاعتماد أولًا.", en: "Submit the order for approval first." },
  { match: /must be approved before receiving/, ar: "لا يمكن الاستلام قبل اعتماد أمر الشراء.", en: "The order must be approved before receiving." },
  { match: /receiving more than ordered/, ar: "الكمية أكبر من المتبقي في أمر الشراء.", en: "The quantity exceeds what remains on the order." },
  { match: /only once in an order/, ar: "كل صنف يُكتب مرة واحدة في أمر الشراء.", en: "Each item can appear only once in an order." },
  { match: /nothing received can be cancelled/, ar: "لا يمكن إلغاء أمر تم استلام جزء منه.", en: "Orders with receipts cannot be cancelled." },
  { match: /exceeds what is outstanding/, ar: "المبلغ أكبر من المتبقي على فاتورة المورد.", en: "The amount exceeds what is outstanding on the supplier invoice." },
  { match: /release a payment you requested/, ar: "لا يمكنك صرف دفعة طلبتها بنفسك. يلزم مسؤول آخر.", en: "You cannot release a payment you requested." },
  { match: /one payment covers one branch/, ar: "الدفعة الواحدة تخص فرعًا واحدًا.", en: "One payment covers one branch." },
  { match: /choose at least one supplier invoice/, ar: "اختر فاتورة مورد واحدة على الأقل.", en: "Choose at least one supplier invoice." },
  { match: /payment already/, ar: "تم اتخاذ قرار في هذه الدفعة بالفعل.", en: "This payment has already been decided." },
  { match: /add at least one line/, ar: "أضف صنفًا واحدًا على الأقل.", en: "Add at least one line." },
  { match: /devices change only through|laser sessions change only through|packages change only through/, ar: "هذا التغيير يتم من الشاشة المخصصة فقط.", en: "This change can only be made from its screen." },
  { match: /asset number or serial number already registered/, ar: "رقم الأصل أو الرقم التسلسلي مسجل من قبل.", en: "Asset number or serial number already registered." },
  { match: /asset number and name are required/, ar: "رقم الأصل والاسم مطلوبان.", en: "Asset number and name are required." },
  { match: /counter reading is lower than the last recorded/, ar: "القراءة أقل من آخر قراءة مسجلة للعداد. العداد لا يرجع للخلف إلا بتصفير بعد صيانة.", en: "The reading is lower than the last recorded counter value. Counters only go back through a service reset." },
  { match: /this device has no usage counter/, ar: "هذا الجهاز ليس له عداد.", en: "This device has no usage counter." },
  { match: /describe the problem or the planned work/, ar: "اكتب المشكلة أو العمل المطلوب.", en: "Describe the problem or the planned work." },
  { match: /describe the work done/, ar: "اكتب ما تم عمله.", en: "Describe the work done." },
  { match: /record whether the check passed/, ar: "حدد نتيجة المعايرة / الفحص.", en: "Record whether the check passed." },
  { match: /close or cancel the open work orders first/, ar: "أغلق أو ألغِ أوامر الصيانة المفتوحة أولًا.", en: "Close or cancel the open work orders first." },
  { match: /device is retired/, ar: "الجهاز مُستبعد.", en: "The device is retired." },
  { match: /device is out of service/, ar: "الجهاز متوقف للصيانة ولا يمكن استخدامه حتى يُغلق أمر الصيانة.", en: "The device is out of service until maintenance is closed." },
  { match: /calibration is overdue/, ar: "معايرة الجهاز متأخرة. سجّل معايرة ناجحة أولًا.", en: "Device calibration is overdue. Record a passing calibration first." },
  { match: /the patient has not arrived/, ar: "لم يُسجل وصول المريض لهذا الموعد بعد.", en: "The patient has not been checked in for this appointment." },
  { match: /choose a device in this branch/, ar: "اختر جهازًا في هذا الفرع.", en: "Choose a device in this branch." },
  { match: /choose the treatment service/, ar: "اختر خدمة العلاج.", en: "Choose the treatment service." },
  { match: /not available on this device/, ar: "هذا الإعداد (الطول الموجي أو حجم البقعة) غير متاح في الجهاز.", en: "That wavelength or spot size is not available on this device." },
  { match: /outside the approved range/, ar: "القيمة خارج نطاق الإعدادات المعتمدة للجهاز.", en: "The value is outside the device's approved range." },
  { match: /signed laser session cannot be modified/, ar: "الجلسة موقّعة ولا يمكن تعديلها. أضف ملاحظة لاحقة.", en: "The session is signed. Add an addendum instead." },
  { match: /laser session is already signed/, ar: "الجلسة موقّعة بالفعل.", en: "The session is already signed." },
  { match: /record the skin type/, ar: "حدد نوع البشرة (فيتزباتريك) قبل التوقيع.", en: "Record the skin type (Fitzpatrick) before signing." },
  { match: /answer every checklist question/, ar: "أجب عن كل أسئلة الموانع قبل التوقيع.", en: "Answer every contraindication question before signing." },
  { match: /a doctor must review/, ar: "يوجد مانع للعلاج. يجب أن يراجع الطبيب ويوقّع مع كتابة السبب.", en: "A contraindication is present. A doctor must review and sign with a reason." },
  { match: /write the clinical reason/, ar: "يوجد مانع للعلاج. اكتب السبب الطبي للمتابعة (10 أحرف على الأقل).", en: "A contraindication is present. Write the clinical reason for proceeding (at least 10 characters)." },
  { match: /add at least one treated area/, ar: "أضف منطقة معالجة واحدة على الأقل.", en: "Add at least one treated area." },
  { match: /enter the device counter before and after/, ar: "اكتب قراءة عداد الجهاز قبل الجلسة وبعدها.", en: "Enter the device counter before and after the session." },
  { match: /counter after must be greater/, ar: "قراءة العداد بعد الجلسة يجب أن تكون أكبر من القراءة قبلها.", en: "The counter after must be greater than the counter before." },
  { match: /counter before .* is lower than the last recorded reading/, ar: "قراءة العداد قبل الجلسة أقل من آخر قراءة مسجلة للجهاز. راجع القراءة.", en: "The counter before is lower than the device's last recorded reading. Check the reading." },
  { match: /pulses do not match the counter/, ar: "مجموع نبضات المناطق والاختبار لا يساوي فرق العداد. راجع الأرقام.", en: "Pulses per area plus the test spot do not equal the counter difference." },
  { match: /package belongs to another patient/, ar: "الباقة تخص مريضًا آخر.", en: "The package belongs to another patient." },
  { match: /package is (used|expired|cancelled)/, ar: "الباقة غير سارية (مستهلكة أو منتهية أو ملغاة).", en: "The package is no longer active (used, expired or cancelled)." },
  { match: /package expired on/, ar: "انتهت صلاحية الباقة.", en: "The package has expired." },
  { match: /package does not cover this service/, ar: "الباقة لا تغطي هذه الخدمة.", en: "The package does not cover this service." },
  { match: /package is limited to another branch/, ar: "الباقة مقصورة على فرع آخر.", en: "The package is limited to another branch." },
  { match: /no sessions left/, ar: "لا توجد جلسات متبقية في الباقة.", en: "No sessions left in this package." },
  { match: /package invoice .* is not fully paid/, ar: "فاتورة الباقة لم تُسدد بالكامل. تُستخدم الجلسات بعد السداد.", en: "The package invoice is not fully paid. Sessions can be used once it is paid." },
  { match: /packages are sold from the package screen/, ar: "الباقات تُباع من ملف المريض (بيع باقة) وليس كسطر فاتورة.", en: "Packages are sold from the patient file, not as an invoice line." },
  { match: /package already used/, ar: "تم استخدام جلسات من الباقة ولا يمكن إلغاء فاتورتها.", en: "Sessions were already used from this package; its invoice cannot be voided." },
  { match: /package refunds are not supported/, ar: "استرداد الباقات غير متاح بعد. ألغِ فاتورة الباقة غير المستخدمة أو ارجع للإدارة المالية.", en: "Package refunds are not supported yet. Void an unused package invoice or contact finance." },
  { match: /package is not available|not sold in this branch/, ar: "الباقة غير متاحة للبيع هنا.", en: "This package is not available here." },
  { match: /discount must be below the package price/, ar: "الخصم يجب أن يكون أقل من سعر الباقة.", en: "The discount must be below the package price." },
  { match: /package code already exists/, ar: "كود الباقة مستخدم.", en: "The package code already exists." },
  { match: /code and name are required/, ar: "الكود والاسم مطلوبان.", en: "Code and name are required." },
  { match: /package template not found/, ar: "الباقة غير موجودة، ولا يمكن تغيير الخدمة المرتبطة بها.", en: "Package not found; its service cannot change." },
  { match: /a reset must be lower than the current reading/, ar: "التصفير يكون لقراءة أقل من الحالية (بعد تغيير قطعة). للقراءة الأعلى سجّل قراءة عادية.", en: "A reset must be lower than the current reading; record a normal reading instead." },
  { match: /reading is required/, ar: "اكتب قراءة العداد.", en: "Enter the counter reading." },
  { match: /already on an invoice — remove that line/, ar: "هذه الجلسة مسجلة على فاتورة بالفعل. احذف السطر من الفاتورة أو لا تستخدم الباقة.", en: "This session is already on an invoice. Remove that line or do not use the package." },
  { match: /covered by a package and cannot be invoiced again/, ar: "هذه الجلسة خُصمت من باقة ولا يمكن فوترتها مرة أخرى.", en: "This session was covered by a package and cannot be invoiced again." },
  { match: /package is already .* its invoice cannot be voided/, ar: "الباقة مغلقة (منتهية أو مستهلكة) ولا يمكن إلغاء فاتورتها.", en: "The package is closed (expired or used); its invoice cannot be voided." },
  { match: /note is required/, ar: "الملاحظة مطلوبة.", en: "A note is required." },
  { match: /you can prepare only your own treatment plans/, ar: "يمكنك إعداد خطط مرضاك فقط.", en: "You can prepare only your own treatment plans." },
  { match: /only a draft plan can be edited/, ar: "لا يمكن تعديل الخطة بعد إصدار عرض السعر؛ أعدها مسودة أولًا.", en: "The plan can't be edited after the quotation; revise it first." },
  { match: /only a draft plan can be proposed/, ar: "عرض السعر يصدر من المسودة فقط.", en: "Only a draft plan can be proposed." },
  { match: /only a proposed plan can be (revised|accepted)/, ar: "هذه الخطوة لعرض سعر صادر فقط.", en: "This step applies to an issued quotation only." },
  { match: /add at least one treatment line/, ar: "أضف بند علاج واحدًا على الأقل.", en: "Add at least one treatment line." },
  { match: /plan title is required/, ar: "عنوان الخطة مطلوب.", en: "The plan title is required." },
  { match: /choose a service for every line/, ar: "اختر خدمة لكل سطر.", en: "Choose a service for every line." },
  { match: /has no price in this branch/, ar: "هذه الخدمة ليس لها سعر في قائمة أسعار الفرع. أضف السعر من الإعدادات.", en: "This service has no price in the branch price list. Add it in Settings." },
  { match: /tooth must be an FDI number/, ar: "رقم السن بترقيم FDI: من 11 إلى 48 للدائمة ومن 51 إلى 85 للبنية.", en: "Tooth numbers use FDI: 11–48 permanent, 51–85 primary." },
  { match: /surfaces are up to 5 letters/, ar: "الأسطح حتى 5 حروف من M O D B L I F P.", en: "Surfaces: up to 5 letters from M O D B L I F P." },
  { match: /quotation validity must be/, ar: "صلاحية العرض من 1 إلى 180 يومًا.", en: "Quotation validity is 1 to 180 days." },
  { match: /the quotation expired/, ar: "انتهت صلاحية عرض السعر. أعد الخطة مسودة وأصدر عرضًا جديدًا.", en: "The quotation expired. Revise the plan and issue a new one." },
  { match: /record how the patient accepted/, ar: "حدد طريقة موافقة المريض.", en: "Record how the patient accepted." },
  { match: /installment schedule must have/, ar: "جدول الأقساط من 1 إلى 36 قسطًا.", en: "The schedule needs 1 to 36 installments." },
  { match: /each installment needs a positive amount/, ar: "كل قسط يحتاج مبلغًا أكبر من صفر.", en: "Each installment needs a positive amount." },
  { match: /installment dates must start today/, ar: "تواريخ الأقساط تبدأ من اليوم أو بعده وبالترتيب.", en: "Installment dates start today or later, in order." },
  { match: /installments add up to .* but the plan total is/, ar: "مجموع الأقساط لا يساوي إجمالي الخطة.", en: "The installments do not add up to the plan total." },
  { match: /the plan must be accepted before work is recorded/, ar: "يجب تسجيل موافقة المريض على الخطة أولًا.", en: "The plan must be accepted first." },
  { match: /this item is already/, ar: "هذا البند مسجل بالفعل.", en: "This item is already recorded." },
  { match: /no completed items to bill/, ar: "لا توجد بنود منفذة لم تُفوتر.", en: "No completed items to bill." },
  { match: /payments are taken only on accepted plans/, ar: "تُحصّل الأقساط على الخطط المقبولة فقط.", en: "Installments are taken only on accepted plans." },
  { match: /plan belongs to another patient/, ar: "الخطة تخص مريضًا آخر.", en: "The plan belongs to another patient." },
  { match: /exceeds the advance balance/, ar: "المبلغ أكبر من الرصيد المقدم المتاح للمريض.", en: "The amount exceeds the patient's available advance." },
  { match: /applied with its own button/, ar: "الخصم من الرصيد المقدم يتم بزر «الخصم من الرصيد المقدم».", en: "Use the “Pay from the advance balance” button." },
  { match: /refunds are paid in cash, card, transfer or wallet/, ar: "الاسترداد يُصرف نقدًا أو ببطاقة أو تحويل أو محفظة.", en: "Refunds are paid in cash, card, transfer or wallet." },
  { match: /appointment belongs to another patient/, ar: "الموعد يخص مريضًا آخر.", en: "The appointment belongs to another patient." },
  { match: /choose a dental laboratory/, ar: "اختر معمل أسنان.", en: "Choose a dental laboratory." },
  { match: /describe the lab work/, ar: "اكتب نوع عمل المعمل.", en: "Describe the lab work." },
  { match: /the due date cannot be in the past/, ar: "موعد التسليم لا يكون في الماضي.", en: "The due date cannot be in the past." },
  { match: /a lab case cannot move from/, ar: "لا يمكن نقل طلب المعمل لهذه الحالة من حالته الحالية.", en: "The lab case cannot move to that status from its current one." },
  { match: /the bill must come from the case's laboratory/, ar: "الفاتورة يجب أن تكون من معمل الطلب نفسه.", en: "The bill must come from the case's laboratory." },
  { match: /lab case is cancelled/, ar: "طلب المعمل ملغي.", en: "The lab case is cancelled." },
  { match: /close the work order before recording its bill/, ar: "أغلق أمر الصيانة قبل تسجيل فاتورته.", en: "Close the work order before recording its bill." },
  { match: /this supplier invoice number is already recorded/, ar: "رقم فاتورة المورد مسجل من قبل.", en: "This supplier invoice number is already recorded." },
  { match: /supplier invoice number is required/, ar: "رقم فاتورة المورد مطلوب.", en: "The supplier invoice number is required." },
  { match: /the bill date cannot be in the future/, ar: "تاريخ الفاتورة لا يكون في المستقبل.", en: "The bill date cannot be in the future." },
  { match: /cannot confirm a bill you recorded/, ar: "لا يمكنك تأكيد فاتورة سجّلتها بنفسك. يلزم مسؤول آخر.", en: "You cannot confirm a bill you recorded; another approver is required." },
  { match: /bill .* must be confirmed by an approver before payment/, ar: "هذه الفاتورة تحتاج تأكيد مسؤول قبل الدفع.", en: "This bill must be confirmed by an approver before payment." },
  { match: /this patient is not under your care/, ar: "هذا المريض ليس من مرضاك (لا يوجد له موعد أو زيارة معك).", en: "This patient is not under your care (no appointment or visit with you)." },
  { match: /the case has not been sent to the lab yet/, ar: "لم يُرسل الطلب للمعمل بعد؛ تُسجل الفاتورة بعد الإرسال.", en: "The case has not been sent to the lab yet; record the bill after sending." },
  { match: /the bill must come from the work order's vendor/, ar: "الفاتورة يجب أن تكون من جهة الصيانة المسجلة في أمر الصيانة.", en: "The bill must come from the work order's vendor." },
  { match: /bill is already void/, ar: "الفاتورة ملغاة بالفعل.", en: "The bill is already void." },
  { match: /bill .* is void/, ar: "هذه الفاتورة ملغاة.", en: "This bill is void." },
  { match: /only unpaid bills with no pending payment can be voided/, ar: "يمكن إلغاء الفاتورة غير المدفوعة فقط وبدون طلب دفع معلق.", en: "Only unpaid bills with no pending payment can be voided." },
  { match: /the package invoice is not fully paid/, ar: "فاتورة الباقة غير مسددة بالكامل — ألغِ الباقة غير المستخدمة بدلًا من الاسترداد.", en: "The package invoice is not fully paid — void the unused package instead." },
  { match: /only an active package can be/, ar: "الإجراء متاح للباقة السارية فقط.", en: "Only an active package allows this." },
  { match: /the fee must be between 0 and the unused value/, ar: "الرسوم بين صفر وقيمة الجلسات غير المستخدمة.", en: "The fee is between 0 and the unused value." },
  { match: /refunds are paid in cash, card, transfer or wallet/, ar: "الاسترداد نقدًا أو ببطاقة أو تحويل أو محفظة.", en: "Refunds are paid in cash, card, transfer or wallet." },
  { match: /package_refunds_open_uq|duplicate key.*package_refunds/, ar: "يوجد طلب استرداد مفتوح لهذه الباقة.", en: "A refund of this package is already open." },
  { match: /a refund of this package is in progress/, ar: "يوجد استرداد جارٍ لهذه الباقة؛ لا يمكن استخدام جلسات أو تحويلها.", en: "A refund of this package is in progress." },
  { match: /the package changed since the request/, ar: "تغيرت الباقة بعد الطلب؛ ارفضه وقدّم طلبًا جديدًا.", en: "The package changed since the request; reject it and request again." },
  { match: /use the package refund for package invoices/, ar: "فواتير الباقات تُسترد من «استرداد الباقة» في ملف المريض.", en: "Package invoices are refunded from the package refund in the patient file." },
  { match: /choose another patient/, ar: "اختر مريضًا آخر.", en: "Choose another patient." },
  { match: /the lot was not received on this receipt/, ar: "التشغيلة ليست من هذا الاستلام.", en: "The lot was not received on this receipt." },
  { match: /return quantity must be between 0 and what is in stock/, ar: "كمية الإرجاع لا تتجاوز الرصيد.", en: "The return quantity cannot exceed the stock." },
  { match: /enter a quantity to return/, ar: "أدخل كمية للإرجاع.", en: "Enter a quantity to return." },
  { match: /a return for this receipt is already waiting/, ar: "يوجد مرتجع لنفس الاستلام بانتظار الاعتماد.", en: "A return for this receipt is already waiting for approval." },
  { match: /cannot approve a return you recorded/, ar: "لا يمكنك اعتماد مرتجع سجلته بنفسك.", en: "You cannot approve a return you recorded." },
  { match: /a pending supplier payment covers this delivery/, ar: "يوجد طلب دفع معلق لهذا الاستلام؛ قرّر فيه أولًا.", en: "A pending supplier payment covers this delivery; decide it first." },
  { match: /nothing left to refund/, ar: "لا يوجد رصيد غير مستخدم في الباقة لاسترداده.", en: "There is no unused balance left to refund." },
  { match: /only .* left in lot .* reject and record the return again/, ar: "الكمية المتبقية في التشغيلة أقل من المرتجع. ارفض الطلب وسجّله من جديد.", en: "The lot now holds less than the return. Reject it and record the return again." },
  { match: /only blocked, failed or rejected documents can be sent again/, ar: "يمكن إعادة إرسال المستندات الموقوفة أو الفاشلة أو المرفوضة فقط.", en: "Only blocked, failed or rejected documents can be sent again." },
  { match: /withholding tax must be 0 to 100/, ar: "نسبة ضريبة الخصم من المنبع بين 0 و100.", en: "Withholding tax must be between 0 and 100." },
  { match: /basis must be invoiced or collected/, ar: "اختر متى يستحق نصيب الطبيب.", en: "Choose when the doctor's share becomes due." },
  { match: /doctors are paid by bank transfer or cash/, ar: "صرف مستحقات الأطباء بالتحويل البنكي أو نقدًا فقط.", en: "Doctors are paid by bank transfer or cash." },
  { match: /more than the withholding tax due/, ar: "المبلغ أكبر من الضريبة المستحقة.", en: "The amount is more than the tax due." },
  { match: /second, different approver is required above the limit/, ar: "الأمر فوق حد الاعتماد ويحتاج معتمدًا ثانيًا مختلفًا.", en: "Above the limit a second, different approver is required." },
  { match: /payments above .* need the higher approval/, ar: "الدفعة أعلى من حد الاعتماد — يصرفها مدير المركز.", en: "This payment is above the limit — the center director releases it." },
  { match: /choose the VAT treatment/, ar: "حدد معالجة ضريبة المشتريات في إعدادات المشتريات أولًا.", en: "Choose the purchase VAT treatment in purchasing settings first." },
  { match: /tax invoice number/, ar: "اكتب رقم فاتورة المورد الضريبية.", en: "Enter the supplier's tax invoice number." },
  { match: /already returned on this delivery; VAT can no longer change/, ar: "تم إرجاع أصناف من هذا الاستلام؛ لا يمكن تعديل الضريبة.", en: "Goods were returned on this delivery; its VAT can no longer change." },
  { match: /already paid beyond the new total/, ar: "المدفوع أكبر من الإجمالي الجديد.", en: "The delivery is already paid beyond the new total." },
  { match: /the credit has only .* left/, ar: "المبلغ أكبر من المتبقي في الرصيد الدائن.", en: "The amount is more than what is left of the credit." },
  { match: /return already/, ar: "تم القرار على المرتجع بالفعل.", en: "The return was already decided." },
  { match: /payroll setup incomplete: (.*)/, ar: "إعدادات الرواتب ناقصة — راجع إعدادات الرواتب وملفات الموظفين (نسب التأمينات، الإضافي، التأخير، شرائح الضريبة، الأجر التأميني).", en: "Payroll setup is incomplete — check the payroll settings and employee files (insurance rates, overtime, lateness, tax brackets, insured wages)." },
  { match: /payroll for this month is already prepared/, ar: "كشف هذا الشهر معد بالفعل. ألغه أولًا لإعادة الإعداد.", en: "This month's payroll is already prepared. Cancel it to prepare again." },
  { match: /cannot prepare a future month/, ar: "لا يمكن إعداد رواتب شهر لم يبدأ.", en: "Cannot prepare a future month." },
  { match: /separation of duties: you cannot approve a payroll you prepared/, ar: "لا يمكنك اعتماد كشف أعددته.", en: "You cannot approve a payroll you prepared." },
  { match: /separation of duties: you cannot approve a payroll that includes your own salary/, ar: "لا يمكنك اعتماد كشف فيه راتبك.", en: "You cannot approve a payroll that includes your own salary." },
  { match: /the payer must be different/, ar: "الصرف يتم بواسطة شخص غير من أعد أو اعتمد الكشف.", en: "The payer must be different from who prepared and approved." },
  { match: /a payslip has a negative net pay/, ar: "يوجد موظف صافي راتبه سالب؛ عدّل وأعد الإعداد.", en: "A payslip has a negative net; fix it and prepare again." },
  { match: /only an approved payroll can be paid/, ar: "يُصرف الكشف بعد اعتماده فقط.", en: "Only an approved payroll can be paid." },
  { match: /payroll run already/, ar: "حالة الكشف لا تسمح بهذه الخطوة.", en: "The payroll run's status does not allow this." },
  { match: /that month's payroll is already approved/, ar: "رواتب هذا الشهر معتمدة؛ لا يمكن تعديل حضوره أو إجازاته.", en: "That month's payroll is approved; its attendance and leave are locked." },
  { match: /this staff member already has an employee file/, ar: "هذا الشخص له ملف موظف بالفعل.", en: "This staff member already has an employee file." },
  { match: /shift belongs to another branch/, ar: "الوردية تابعة لفرع آخر.", en: "The shift belongs to another branch." },
  { match: /a newer .* amount already exists/, ar: "يوجد مبلغ أحدث لهذا البند؛ اختر تاريخ سريان لاحق.", en: "A newer amount exists; choose a later effective date." },
  { match: /salary change cannot start inside a payroll month that is already approved/, ar: "لا يمكن أن يسري تعديل الراتب داخل شهر رواتبه معتمدة.", en: "A salary change cannot start inside an approved payroll month." },
  { match: /no punches found in the file/, ar: "لم نجد بصمات في الملف (رقم الموظف + التاريخ والوقت).", en: "No punches found in the file (employee id + date and time)." },
  { match: /send 1 to 20,000 punches/, ar: "الملف أكبر من المسموح (20,000 بصمة).", en: "The file is too large (20,000 punches max)." },
  { match: /a punch cannot be in the future/, ar: "البصمة لا تكون في المستقبل.", en: "A punch cannot be in the future." },
  { match: /punch already decided/, ar: "تم القرار على البصمة بالفعل.", en: "The punch was already decided." },
  { match: /cannot approve a punch you entered/, ar: "لا يمكنك اعتماد بصمة سجلتها بنفسك.", en: "You cannot approve a punch you entered." },
  { match: /cannot approve your own attendance/, ar: "لا يمكنك اعتماد حضورك.", en: "You cannot approve your own attendance." },
  { match: /approved overtime must be between/, ar: "الإضافي المعتمد لا يتجاوز الإضافي الفعلي.", en: "Approved overtime cannot exceed the actual overtime." },
  { match: /choose up to two months/, ar: "اختر مدة شهرين بحد أقصى.", en: "Choose up to two months." },
  { match: /no employee file for this account/, ar: "لا يوجد ملف موظف لحسابك.", en: "There is no employee file for your account." },
  { match: /employee is not active/, ar: "الموظف ليس على رأس العمل.", en: "The employee is not active." },
  { match: /split leave that crosses the new year/, ar: "قسّم الإجازة اللي تعدي رأس السنة لطلبين.", en: "Split leave that crosses the new year into two requests." },
  { match: /overlaps another leave request/, ar: "الإجازة تتداخل مع طلب آخر.", en: "The leave overlaps another request." },
  { match: /no working days in that range/, ar: "لا توجد أيام عمل في هذه المدة.", en: "No working days in that range." },
  { match: /not enough .* balance/, ar: "الرصيد لا يكفي.", en: "Not enough balance." },
  { match: /cannot decide your own leave request/, ar: "لا يمكنك اعتماد إجازتك.", en: "You cannot decide your own leave." },
  { match: /leave request already/, ar: "تم القرار على الطلب بالفعل.", en: "The request was already decided." },
  { match: /cannot approve a loan you requested or your own/, ar: "لا يمكنك اعتماد سلفة طلبتها أو تخصك.", en: "You cannot approve a loan you requested or your own." },
  { match: /cannot pay out a loan you approved/, ar: "لا يمكنك صرف سلفة اعتمدتها.", en: "You cannot pay out a loan you approved." },
  { match: /only an approved loan can be paid out/, ar: "تُصرف السلفة بعد اعتمادها.", en: "Only an approved loan can be paid out." },
  { match: /loan already/, ar: "تم القرار على السلفة بالفعل.", en: "The loan was already decided." },
  { match: /choose a bonus or penalty component/, ar: "اختر مكافأة أو جزاء.", en: "Choose a bonus or penalty." },
  { match: /that month's payroll is already prepared/, ar: "كشف هذا الشهر معد؛ ألغه أو سجّل البند في الشهر التالي.", en: "That month's payroll is prepared; cancel it or use next month." },
  { match: /brackets must start at 0/, ar: "الشرائح تبدأ من صفر ومتتالية بدون فجوات.", en: "Brackets start at 0 with no gaps." },
  { match: /the last bracket must be open-ended/, ar: "آخر شريحة بدون حد أعلى.", en: "The last bracket has no upper limit." },
  { match: /tax brackets cannot change inside a payroll month/, ar: "لا يمكن تغيير الشرائح داخل شهر رواتبه معتمدة.", en: "Brackets cannot change inside an approved payroll month." },
  { match: /the basic salary cannot be switched off/, ar: "لا يمكن إيقاف الأجر الأساسي.", en: "The basic salary cannot be switched off." },
  { match: /payment reference is required/, ar: "مرجع الصرف مطلوب.", en: "A payment reference is required." },
  { match: /end date is before the hire date/, ar: "تاريخ الانتهاء قبل تاريخ التعيين.", en: "The end date is before the hire date." },
  { match: /only the treating doctor sets the follow-up/, ar: "الطبيب المعالج فقط هو اللي يحدد موعد المتابعة.", en: "Only the treating doctor sets the follow-up." },
  { match: /follow-up date must be between tomorrow and one year ahead/, ar: "موعد المتابعة من بكرة لحد سنة قدام.", en: "The follow-up date is from tomorrow up to one year ahead." },
  { match: /outside the 24-hour WhatsApp window/, ar: "مر أكتر من ٢٤ ساعة على آخر رسالة من المريض؛ واتساب لا يسمح برد حر. اتصل بالمريض.", en: "More than 24 hours since the patient's last message; WhatsApp does not allow a free reply. Call the patient." },
  { match: /this conversation is a phone call/, ar: "المحادثة دي مكالمة؛ اتصل بالمريض.", en: "This conversation is a phone call; call the patient." },
  { match: /conversation is already closed/, ar: "المحادثة مغلقة بالفعل.", en: "The conversation is already closed." },
  { match: /only a conversation handled by staff can be handed back/, ar: "المحادثة مش مع فريق العمل أصلًا.", en: "The conversation is not with staff." },
  { match: /a note is required to close/, ar: "اكتب سبب الإغلاق أو ما تم.", en: "Write why it is closed or what was done." },
  { match: /message text is required/, ar: "اكتب نص الرسالة.", en: "Type the message." },
  { match: /escalation is already (resolved|acknowledged)/, ar: "التنبيه تم التعامل معه بالفعل.", en: "The escalation was already handled." },
  { match: /a resolution note is required/, ar: "اكتب ما تم.", en: "Write what was done." },
  { match: /care_agent_settings_check|contact_from/, ar: "ساعة البداية لازم تكون قبل ساعة النهاية.", en: "The start time must be before the end time." },
  { match: /lab cost share must be 0 to 100/, ar: "نصيب الطبيب من تكلفة المعمل من 0 إلى 100%.", en: "The lab cost share is 0 to 100%." },
  { match: /cannot confirm a receipt you recorded/, ar: "لا يمكنك تأكيد استلام سجّلته بنفسك. يلزم مسؤول آخر.", en: "You cannot confirm a receipt you recorded; another approver is required." },
  { match: /must be confirmed by an approver before payment/, ar: "هذا الاستلام تم بدون أمر شراء ويجب أن يؤكده مسؤول (غير من سجّله) قبل الدفع.", en: "This receipt has no purchase order and must be confirmed by an approver (not the receiver) before payment." },
  { match: /only partly received orders can be closed/, ar: "يمكن إغلاق الأوامر المستلمة جزئيًا فقط.", en: "Only partly received orders can be closed." },
  { match: /quantity and unit cost are required/, ar: "الكمية وسعر الوحدة مطلوبان وأكبر من صفر.", en: "Quantity and unit cost are required and must be above zero." },
  { match: /separation of duties/, ar: "هذه الخطوة يجب أن ينفذها مستخدم آخر (فصل المهام).", en: "Another user must perform this step (separation of duties)." },
  { match: /medically approve/, ar: "آخر من عدّل المحتوى لا يعتمده طبيًا.", en: "The last editor cannot medically approve this content." },
  { match: /permission denied|row-level security|42501/, ar: "ليست لديك صلاحية لتنفيذ هذا الإجراء.", en: "You do not have permission to do this." },
];

export function friendlyError(message: string | undefined | null, locale: Locale): string {
  const text = message ?? "";
  const rule = RULES.find((r) => r.match.test(text));
  if (rule) return locale === "ar" ? rule.ar : rule.en;
  return locale === "ar" ? "حدث خطأ غير متوقع. لم يُحفظ شيء." : "Something went wrong. Nothing was saved.";
}

// Patient-facing wording for the portal (never reveals whether another file exists).
const PORTAL_RULES: Rule[] = [
  { match: /no longer available/, ar: "هذا الموعد لم يعد متاحًا. اختر وقتًا آخر.", en: "That time is no longer available. Please choose another." },
  { match: /too many pending requests/, ar: "لديك 3 طلبات حجز بانتظار التأكيد. سنتواصل معك قريبًا.", en: "You already have 3 booking requests awaiting confirmation. We will contact you soon." },
  { match: /online cancellation closes/, ar: "الإلغاء من الحساب غير متاح قبل الموعد مباشرة. تواصل معنا عبر واتساب أو الهاتف.", en: "Online cancellation is closed this close to the appointment. Please contact us by WhatsApp or phone." },
  { match: /can no longer be cancelled online/, ar: "لا يمكن إلغاء هذا الموعد من الحساب.", en: "This appointment can no longer be cancelled online." },
  { match: /too many requests/, ar: "وصلت للحد اليومي للطلبات. حاول غدًا أو تواصل معنا.", en: "You have reached today's request limit. Try tomorrow or contact us." },
  { match: /survey already submitted/, ar: "تم إرسال تقييمك لهذه الزيارة من قبل. شكرًا لك.", en: "You already rated this visit. Thank you." },
  { match: /survey is available after the visit/, ar: "التقييم متاح بعد انتهاء الزيارة.", en: "Rating is available after the visit." },
  { match: /no matching patient file/, ar: "لم نجد ملفًا بهذا الرقم ورقم الموبايل معًا. تأكد من البيانات.", en: "No file matches that number and mobile together. Please check the details." },
  { match: /nothing to pay/, ar: "لا يوجد مبلغ مستحق على هذه الفاتورة.", en: "There is nothing to pay on this invoice." },
  { match: /check constraint|violates|invalid input/, ar: "تأكد من البيانات المدخلة.", en: "Please check the details you entered." },
  { match: /not found|permission denied|42501/, ar: "هذا الإجراء غير متاح لحسابك.", en: "This action is not available for your account." },
];

export function portalError(message: string | undefined | null, lang: Locale): string {
  const text = message ?? "";
  const rule = PORTAL_RULES.find((r) => r.match.test(text));
  if (rule) return lang === "ar" ? rule.ar : rule.en;
  return lang === "ar" ? "حدث خطأ غير متوقع. حاول مرة أخرى." : "Something went wrong. Please try again.";
}
